import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import SmoothScroll from "@/Provider/SmoothScroll";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Optional: CSS variable
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vacation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <SmoothScroll>
          <Navbar />
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
